print([
    ("html", "Wörter aus Fremdsprachen sind per HTML gekennzeichnet", "Beispiel <html lang=\"de\">", "manuell"),
    ("html", "Bei Zitaten fremdsprachige Wörter oder Sätze in Blockquote-Element kennzeichnen", "Beispiel <blockquote lang=\"es\"", "manuell"),
    ("html", "Aufzählungen im HTML-Quelltext als Listen formatieren", "ul, ol, dl", "manuell"),
    ("html", "Zitate als <blockquote>- und <cite>- Elemente in Quelltext einbinden", "", "manuell"),
    ("html", "Beschriftung Formularfelder mittels HTML-Tag <label> erfolgt", "Platzhalter-Texte in Formularfeldern sind nicht ausreichend", "manuell"),
    ("html", "Inhaltlich zusammengehörige Gruppen in mehrteiligen Formularen durch <fieldset> gekennzeichnet", "", "manuell"),
    ("html", "Richtige Reihenfolge von Überschriftenebenen beachtet", "Seite beginnt mit <h1>, es folgen <h2> bis maximal <h6>; in Reihenfolge <h1> zu <h6> darf keine Ebene übersprungen werden, in Reihenfolge <h6> zu <h1> dürfen Ebenen übersprungen werden", "manuell"),
    ("html", "Warnung der Nutzer*innen, dass eingegebene Daten bei Inaktivität verloren gehen", "Ausnahme: Die Daten bleiben für 20 Stunden erhalten", "manuell"),
    ("html", "Gleichbleibende Navigation auf der Webseite", "", "manuell"),
    ("html", "Gleicher Aufbau von Funktionen auf einer Webseite", "", "manuell"),
    ("html", "Sich wiederholende Elemente sind gruppiert oder durch Überschriften ausgezeichnet und können mit Sprungmarken übergangen werden", "", "manuell"),
    ("html", "Mehrere Methoden vorhanden, um auf Inhalte zuzugreifen", "Navigation + Suchfunktion und/oder Inhaltsverzeichnis", "manuell"),
    ("html", "Webseiter mit Tabulatortaste bedienbar", "", "manuell"),
    ("html", "Elemente im Fokus-Zustand bei Ansteuerung mit Tastatur gekennzeichnet", "", "manuell"),
    ("html", "Bedienbarkeit der Webseite erfordert keine Zeiteinteilung in der Tastaturnutzung", "Beispiel: Die Enter-Taste darf nicht 2 Mal im Abstand von 5 Sekunden gedrückt werden, damit das Menü geöffnet wird.", "manuell"),
    ("html", "Der Tastaturfokus ist bei keinem Element der Webseite blockiert", "", "manuell"),
    ("html", "Anwender*innen können jedes Element mit der Tastatur ansteuern und verlassen", "", "manuell"),
    ("html", "Akronyme und Abkürzungen besonders definieren", "Beispiel: <abbr title=\"United Nations Organization\">UNO</abbr>", "manuell"),
    ("kontrast", "Bedienelemente mit ausreichendem Kontrast", "Kontrastverhältnis beträgt mindestens 3:1", "manuell"),
    ("kontrast", "Grafische Elemente (z.B. Infografiken oder Bedienelemente) mit ausreichendem Kontrast", "Kontrastverhältnis beträgt mindestens 3:1", "manuell"),
    ("kontrast", "Gutes Kontrastverhältnis von Text zu Hintergrund", "Kontrastverhältnis beträgt mindestens 7:1", "manuell"),
    ("kontrast", "Gutes Kontrastverhältnis von Text ab Schriftgröße 8pt. zu Hintergrund", "Kontrastverhältnis beträgt mindestens 4,5:1", "manuell"),
    ("kontrast", "Gutes Kontrastverhältnis von Text ab Schriftgröße 4pt. und fettgedruckt - zu Hintergrund", "Kontrastverhältnis beträgt mindestens 4,5:1", "manuell"),
    ("kontrast", "Texte in Grafiken auf Kontrastverhältnis untersuchen", "Keine automatische Prüfung möglich; Empfehlung: manuelle Prüfung mit einem Color Contrast Analyzer", "manuell"),
    ("kontrast", "Transparente Texte auf Kontrastverhältnis untersuchen", "Keine automatische Prüfung möglich; Empfehlung: manuelle Prüfung mit einem Color Contrast Analyzer", "manuell"),
    ("kontrast", "Textlogos", "Hier muss kein Kontrast berücksichtigt werden", "manuell"),
    ("kontrast", "Hervorhebung von Links", "Links nicht nur durch Farbe hervorheben; ggf. durch Symbole oder Unterstreichung zusätzlich kenntlich machen. Wenn nur durch Farbe kenntlich gemacht, dann mind. Kontrastverhältnis 3:1 im Vergleich zu nicht hervorgehobenen Text", "manuell"),
    ("kontrast", "Pflichtfelder in Formularen nicht ausschließlich durch Farbe hervorgehoben", "Wenn nur durch Farbe, dann mindestens Kontrastverhältnis 3:1 im Vergleich zu nicht hervorgehobenen Text. Pflichtfelder zusätzlich kennzeichnen (z.B. Sternchen) und Symbolik am Anfang erläutern", "manuell"),
    ("kontrast", "Fehlermeldungen in Formularen nicht ausschließlich durch Farben kenntlich gemacht", "z.B. unausgefüllte Pflichtfelder nicht nur durch farbliche Umrandungen ausgewiesen, sondern auch durch einen Texthinweis oder mindestens ein Kontrastverhältnis von 3:1", "manuell"),
    ("kontrast", "Überschriften nicht ausschließlich durch Farbe markiert", "Überschriften bspw. in HTML mit <h1> etc. gekennzeichnet", "manuell"),
    ("kontrast", "Ausgewählte Menüeinträge nicht ausschließlich durch Farbe kenntlich machen", "Zusätzlich kann der ausgewählte Menüeintrag bspw. unterstrichen werden oder das Kontrastverhältnis beträgt mindestens 3:1", "manuell"),
    ("kontrast", "Ausreichendes Kontrastverhältnis bei Bedienelementen mit Rahmen und ohne Text", "Rahmen hat ein Kontrastverhältnis von mindestens 3:1", "manuell"),
    ("kontrast", "Ausreichendes Kontrastverhältnis für Systemfokus zwischen Fokus und Hintergrund", "Wenn der Systemfokus nur durch Farbe kenntlich gemacht ist, muss das Kontrastverhältnis mindestens 3:1 betragen", "manuell"),
    ("kontrast", "Ausreichende Hervorhebung von Zeilen und Zellen in Tabellen", "Hervorhebung durch fettgedruckt oder zusätzlich umrandet oder Farbkontrast von mindestens 3:1 zu nicht hervorgehobenen Zeilen/Zellen", "manuell"),
    ("links", "Eindeutige Link-Bezeichnungen wählen", "\"hier\" als Link ist z.B. nicht aussagekräftig; es sei denn, aus dem Kontext des Links geht hervor, was damit gemeint ist", "manuell"),
    ("links", "Hervorhebung von Links", "Links nicht nur durch Farbe hervorheben; ggf. durch vorangestellte Symbole, Fettung oder Unterstreichung zusätzlich kenntlich machen", "manuell"),
    ("links", "Ziel des Links benennen", "Vermerken, ob sich bspw. eine neue Seite oder ein Dokument öffnet; bei hinterlegten Dokumenten ist die Angabe, dass es sich um ein Dokument handelt, Pflicht", "manuell"),
    ("links", "Alternativtext für Bedienelemente (z.B. Lupen-Icon für die Suche)", "Funktion benennen (z.B. suchen); Benennungen immer so kurz wie möglich", "manuell"),
    ("titel", "Zweiteiliger Aufbau Seitentitel", "Seitentitel bestehend aus individuellem und allgemeinem Seitentitel angeben, getrennt durch Bindestrich oder ähnlichem", "manuell"),
    ("titel", "Einheitlicher allgemeiner Seitentitel", "Allgemeiner Seitentitel (z.B. Name der Webseite) immer gleichbleibend", "manuell"),
    ("tabelle", "Layout-Tabellen vermeiden", "Wiedergabe durch Screenreader könnte Nutzende verwirren", "manuell"),
    ("tabelle", "Tabellen für mobile Darstellungen optimieren", "Tabellen auch gut auf Smartphones und Tablets lesbar; sinnvolle Inhaltsumbrüche berücksichtigen", "manuell"),
    ("tabelle", "Richtige Kennzeichnung von Tabellen", "Tabelle mit <Table> einleiten, Tabellenkopf durch <th>, Tabellenzeile durch <tr> und Datenzelle durch <td> kenntlich machen", "manuell"),
    ("tabelle", "Für einfache Datentabellen: Nur eine Spalten- und Zeilenüberschrift verwenden", "Jede Spalte und jede Zeile nur eine Überschrift; keine kombinierten Zellen", "manuell"),
    ("tabelle", "Für komplexe Datentabellen: Eindeutige Zuordnungen erstellen", "Zellen mit header- und id-Attributen für eindeutige Zuordnung versehen", "manuell"),
    ("überschrift", "Überschriften strukturieren", "Überschriftenebenen mit HTML ordnen; maximal 6 Ebenen", "manuell"),
    ("überschrift", "Richtige Reihenfolge der Überschriftenebenen", "Bei Strukturierung von oben nach unten Reihenfolge einhalten (z.B. H1, H2, H3 etc.)", "manuell"),
    ("überschrift", "Sinnvolle Überschriftenlänge", "Überschriften kurz und verständlich halten", "manuell"),
    ("bild", "Alternativtext für nicht verlinkte Bilder", "Objektive Beschreibung was zu sehen ist, in 1-2 Sätzen; gilt nur, wenn nicht als dekoratives Element eingesetzt", "manuell"),
    ("bild", "Alternativtext für Bedienelemente (z.B. Lupen-Icon für die Suche)", "Funktion benennen (z.B. suchen)", "manuell"),
    ("bild", "Alternativtext für verlinkte Bilder", "Objektive Beschreibung, was zu sehen ist, in 1-2 Sätzen und Funktion des Links benennen", "manuell"),
    ("bild", "Dekorative Grafiken (z.B. Trennlinie)", "Benötigen keinen Alternativtext; alt-Attribut in HTML muss vorhanden aber leer sein", "manuell"),
    ("bild", "Alternativen für CAPTCHAs", "Bild-CAPTCHAs mit Audioversion oder nicht bildbasierten Alternativen ergänzen", "manuell"),
    ("dokument", "Textlayout mit Formatvorlagen formatiert", "Schriftgrößen, Schriftarten und Überschriften in den Formatvorlagen definieren", "manuell"),
    ("dokument", "Überschriften 7 - 9 nicht verwendet (für Word)", "Zulässig ist maximal Überschrift 6; Überschriften 7 - 9 werden als normaler Text definiert", "manuell"),
    ("dokument", "Aufzählungen mit Listen-Werkzeug erstellt (für Word)", "Listen sonst nicht als solche von Screenreadern wahrgenommen", "manuell"),
    ("dokument", "Anführungspunkte in Listen enthalten keine relevanten Informationen (z.B. Minus (-) für negativ und Plus (+) für positiv)", "Screenreader lesen Anführungspunkte nicht vor", "manuell"),
    ("dokument", "Fußnoten nach Umwandlung in PDF angepasst", "Word tagt Fußnoten nicht richtig für PDF, weshalb Screenreader diese nicht richtig erfassen", "manuell"),
    ("dokument", "Bilder und Grafiken mit Alternativtexten versehen", "Alternativtexte direkt in Word erstellbar", "manuell"),
    ("dokument", "Dekorative Bilder und Grafiken als solche markiert", "In Word 365 direkt umsetzbar; bei anderen/älteren Versionen nachträglich in PDF ändern", "manuell"),
    ("dokument", "Keine Leerzeilen per Enter enthalten", "Abstände über Absätze markieren; Seitenumbrüche verwenden, um auf neue Seite zu gelangen", "manuell"),
    ("dokument", "Keine Silbentrennung enthalten", "Silbentrennung von Screenreadern nicht erfassbar", "manuell"),
    ("dokument", "Wörter aus Fremdsprachen mit jeweiliger Sprache auszeichnen", "Fremdwörter werden vom Screenreader andernfalls in Deutsch vorgelesen, was unverständlich ist", "manuell"),
    ("dokument", "Textfelder und Grafiken richtig positioniert", "In Word durch richtige Positionierung des Anker-Symbols; in PDF auf richtige Lesereihenfolge im Tag-Baum achten", "manuell"),
    ("dokument", "URL in Linktext hinterlegt", "Bloße Anzeige der URL ist verwirrend, da jedes Zeichen von Screenreadern vorgelesen", "manuell"),
    ("dokument", "Inhaltsverzeichnis vor Veröffentlichung auf Funktionsfähigkeit prüfen", "Im Inhaltsverzeichnis kann zum jeweiligen Punkt navigiert werden", "manuell"),
    ("dokument", "Tabellenüberschriften richtig gekennzeichnet", "Siehe dazu \"Checkliste für Tabellen\"", "manuell"),
    ("dokument", "Tabellenüberschriften auf jeder Seite neu angezeigt", "Tabelle, die über mehrere Seiten geht, auf jeder Seite als eigene Tabelle von Screenreadern erkannt; Wiederholung Überschriften notwendig", "manuell"),
    ("dokument", "Diagramme, SmartArt und Formeln als Bilder eingefügt (für Word)", "Bei Export in PDF keine richtige Tagung; Screenreader erkennen Grafiken nicht richtig", "manuell"),
    ("dokument", "Vor Export in PDF Barrierefreiheits-Prüfungstool verwendet (für Word)", "Je mehr Barrieren bereits behoben, desto weniger Nachbearbeitungen in PDF notwendig", "manuell"),
    ("dokument", "Keine relevanten Informationen in Kopf- und Fußzeilen", "Informationen in Kopf- und Fußzeilen werden grundsätzlich nicht von Screenreadern erfasst", "manuell"),
    ("dokument", "Lesereihenfolge im Tag-Stammbaum prüfen (für PDF)", "Reigenfolge der Tags zeigt Lesereihenfolge für Screenreader an", "manuell"),
    ("dokument", "Dokumententitel vergeben", "Screenreader erfassen Dokumententitel besser als Dateinamen", "manuell"),
    ("ezb", "Erklärung zur Barrierefreiheit (EzB) vorhanden", "EzB ist nach Art. 7 Richtlinie (EU) 2016/2102 zur Verfügung zu stellen", "manuell"),
    ("ezb", "Verlinkung zur EzB an hervorgehobener Stelle des Webauftritts oder auf jeder Webseite vorhanden (gilt auch für mobile Anwendungen)", "Linktext ist aussagekräftig; EzB am besten in Kopf- oder Fußzeile verlinken", "manuell"),
    ("ezb", "EzB anhand Überschrift o.ä. als solche erkennbar", "z.B. Überschrift: Erklärung zur Barrierefreiheit", "manuell"),
    ("ezb", "Geltungsbereich der EzB genannt", "Name der Stelle, Name des Webauftritts/der mobilen Anwendung", "manuell"),
    ("ezb", "Verweis auf Rechtsgrundlage(n)", "Auf EU-Richtlinie 2016/2102, HessBGG und HVBIT verweisen", "manuell"),
    ("ezb", "Aussage, inwieweit die Anforderungen an Barrierefreiheit erfüllt werden", "Stufen: vollständig vereinbar / teilweise vereinbar / nicht vereinbar", "manuell"),
    ("ezb", "Nicht barrierefreihe Inhalte explizit aufgeführt", "\"vollständig vereinbar\" ist nur dann zulässig, wenn keinerlei Barrieren bestehen; jede Barriere einzeln benennen", "manuell"),
    ("ezb", "Begründung, warum Barrieren bestehen", "nicht barrierefreihe Elemente begründen; Barrieren können gruppiert werden, z.B. \"einzelne Grafiken besiten keinen Alternativtext\"", "manuell"),
    ("ezb", "Zeitpunkt, bis wann Barriere abgebaut", "Datumsangabe, bis wann Barriere beseitigt wird; für jede Gruppe von Barrieren angeben; Datumsangabe ist fakultativ", "manuell"),
    ("ezb", "Verwendete Prüfmethode benannt", "Selbstprüfung, durch Dritte, Expertentest etc.", "manuell"),
    ("ezb", "Datum der Erstellung oder der letzten Aktualisierung vorhanden", "", "manuell"),
    ("ezb", "Datum der Erstellung oder letzten Aktualisierung nicht älter als ein Jahr", "", "manuell"),
    ("ezb", "Barrierefreie Alternativen angeben", "sofern vorhanden", "manuell"),
    ("ezb", "Feedback-Mechanismus angegeben und beschrieben", "Link zum Feedback-Mechanismus in EzB einfügen", "manuell"),
    ("ezb", "Kontaktdaten zuständiger Person für barrierefreie Zugänglichkeit vorhanden", "Zuständige Person(en) und/oder Abteilung(en) angeben, die Anfragen zur Barrierefreiheit bearbeiten", "manuell"),
    ("ezb", "Durchsetzungsverfahren beschrieben", "Weiter Informationen auf Webseite https://lbit.hessen.de/durchsetzungs-und-ueberwachungsstelle", "manuell"),
    ("ezb", "Kontakt zur Durchsetzungsstelle aufgeführt", "Links: https://lbit.hessen.de/Ueber-Uns/Ansprechpersonen-Anschrift und https://lbit.hessen.de/Durchsetzungs-und-Ueberwachungsstelle/Durchsetzungsverfahren-beantragen/Formular-Durchsetzungsverfahren", "manuell"),
])